### ISSUE TITLE
Deploy has errors ("Deploy" apresenta erros)

### ISSUE THREAD

**Issue by marcosbarker** [soroushchehresa/github-readme-linkedin#2]
I forked and deployed Vercel, put the environment variables with my [li_at]. When deploying, some errors appear and, finally, it doesn't work.
[👆 translated on google translator]

(Fiz o fork e deploy no Vercel, coloquei as variável de ambiente com meu [li_at]. Na hora do deploy aparecem alguns erros e, por fim não funciona.)

👇 Build logs Vercel:

![image](https://user-images.githubusercontent.com/57602117/110060562-de8d9180-7d44-11eb-9c56-bcba38f59079.png)

**Comment by soroushchehresa** [comment]
@marcosbarker Thank you for the report. 
This issue has been fixed.
